/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"DM Serif Display"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        sans:    ['"Geist"', '"Inter"', 'system-ui', 'sans-serif'],
      },
      colors: {
        sbf: {
          bg:         '#fbf5ec',
          surface:    '#ffffff',
          soft:       '#f4ecd8',
          softer:     '#f9f1e0',
          sand:       '#efe5cf',
          ink:        '#2b1f12',
          text:       '#1e1810',
          muted:      '#7a6a55',
          dim:        '#a8997f',
          line:       '#e3d6b6',
          line2:      '#cebd97',
          accent:     '#d96c3b',
          accent2:    '#3d6e54',
          accent3:    '#e8b658',
          accentSoft: '#fadab9',
          accentBg:   '#fbe8d3',
        },
        gm: {
          bg:         '#f4f0e6',
          surface:    '#ffffff',
          soft:       '#e8e1cf',
          softer:     '#f0e9d6',
          sand:       '#dfd5bd',
          ink:        '#1a2532',
          text:       '#15212c',
          muted:      '#646b78',
          dim:        '#9aa3b1',
          line:       '#d4c9b0',
          line2:      '#b8ab8c',
          accent:     '#2c6e8a',
          accent2:    '#c97132',
          accent3:    '#e6b94a',
          accentSoft: '#c2ddea',
          accentBg:   '#d8e8f0',
        },
        plat: {
          ig:  '#e1306c',
          fb:  '#1877f2',
          fbp: '#1877f2',
          fbg: '#1877f2',
          li:  '#0a66c2',
          wa:  '#25d366',
        },
      },
      borderRadius: {
        sm:   '6px',
        md:   '10px',
        lg:   '14px',
        xl:   '16px',
        '2xl':'18px',
        pill: '20px',
      },
    },
  },
  plugins: [],
};
