// Givat Morgan content calendar — May 28 through Jun 21, 2026
// IDs 30001–30022 — used to detect if already imported
//
// Schedule (Excel: givat_morgan_content_calendar.xlsx):
//  May 28 (Thu)   וכן… גם פה יש פילז ☕ — ריל
//  May 31 (Sun)   5 דברים שלא ציפינו למצוא — קרוסלה
//  Jun 2  (Tue)   שבת בבוקר במורגן היל — ריל
//  Jun 4  (Thu)   עוד כמה רגעים קטנים — קרוסלה
//  Jun 7  (Sun)   לא, זה לא נאפה — ריל
//  Jun 9  (Tue)   למה משפחות ישראליות עוברות — ריל
//  Jun 11 (Thu)   המקומות האהובים בדאונטאון — קרוסלה
//  Jun 14 (Sun)   עוד יום רגוע במורגן היל — ריל
//  Jun 16 (Tue)   לאט לאט זה מרגיש כמו בית — ריל
//  Jun 18 (Thu)   שאלות שישראלים שואלים — קרוסלה FAQ
//  Jun 21 (Sun)   כשאתה מגלה שיש גם פילז וגם שוק איכרים — ריל

export const GM_CALENDAR = [

  // ── May 28 — Philz Reel ──────────────────────────────────────────────────────
  {
    id: 30001,
    title: 'פילז ריל — IG',
    platforms: ['ig'],
    date: new Date('2026-05-28T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'חיכינו לזה הרבה זמן.\nפילז קפה — כן, גם במורגן היל.\nאם זה לא סיבה טובה להגיע לפה, אנחנו לא יודעים מה כן ☕\n\n#givat_morgan',
    hashtags: '#givat_morgan #ישראלים_בבייאריאה #מורגן_היל #קפה #philz #siliconvalley',
    notes: 'קליפ בחנות Philz + שוט של כוס קפה + משה ברכב. טון קל, מצחיק, ריליישן.',
  },
  {
    id: 30002,
    title: 'פילז ריל — FB',
    platforms: ['fbg'],
    date: new Date('2026-05-28T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'חיכינו לזה הרבה זמן.\nפילז קפה — כן, גם במורגן היל.\nאם זה לא סיבה טובה להגיע לפה, אנחנו לא יודעים מה כן ☕\n\n#givat_morgan',
    hashtags: '#givat_morgan #ישראלים_בבייאריאה #מורגן_היל #קפה #philz #siliconvalley',
    notes: 'קליפ בחנות Philz + שוט של כוס קפה + משה ברכב. טון קל, מצחיק, ריליישן.',
  },

  // ── May 31 — 5 Things Carousel ───────────────────────────────────────────────
  {
    id: 30003,
    title: '5 דברים שלא ציפינו — IG',
    platforms: ['ig'],
    date: new Date('2026-05-31T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'כשעברנו לכאן — לא ממש ידענו מה מחכה לנו.\nועכשיו אנחנו לא מצליחים להפסיק לספר על זה לכולם 🌿\n\nשקף 1: שוק האיכרים הכי יפה שראינו\nשקף 2: יקבים ממש כאן — לא צריך לטוס לנאפה\nשקף 3: Philz קפה. כן.\nשקף 4: שבילי טיול שמרגישים כמו קליפורניה הכי יפה\nשקף 5: בלוני אוויר חם מהחלון בבוקר 🎈\n\nאיזה דבר הכי הפתיע אתכם כשעברתם לכאן? ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #ישראלים_בקליפורניה #bayarea #morganhill #farmersmarket',
    notes: 'שקף 1 = תמונה יפה של שוק. כל שקף = מקום אחד + משפט קצר. שקף אחרון = שאלה לקהל.',
  },
  {
    id: 30004,
    title: '5 דברים שלא ציפינו — FB',
    platforms: ['fbg'],
    date: new Date('2026-05-31T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'כשעברנו לכאן — לא ממש ידענו מה מחכה לנו.\nועכשיו אנחנו לא מצליחים להפסיק לספר על זה לכולם 🌿\n\nשקף 1: שוק האיכרים הכי יפה שראינו\nשקף 2: יקבים ממש כאן — לא צריך לטוס לנאפה\nשקף 3: Philz קפה. כן.\nשקף 4: שבילי טיול שמרגישים כמו קליפורניה הכי יפה\nשקף 5: בלוני אוויר חם מהחלון בבוקר 🎈\n\nאיזה דבר הכי הפתיע אתכם כשעברתם לכאן? ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #ישראלים_בקליפורניה #bayarea #morganhill #farmersmarket',
    notes: 'שקף 1 = תמונה יפה של שוק. כל שקף = מקום אחד + משפט קצר. שקף אחרון = שאלה לקהל.',
  },

  // ── Jun 2 — Shabbat Morning Reel ────────────────────────────────────────────
  {
    id: 30005,
    title: 'שבת בבוקר במורגן היל — IG',
    platforms: ['ig'],
    date: new Date('2026-06-02T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שבת בבוקר במורגן היל נראית ככה —\nשוק האיכרים, קפה ביד, ילדים רצים בין הדוכנים,\nואוויר שמריח כמו שאוויר אמור להריח 🌿\n\nאתם גם כאן? תגידו שלום 👋\n\n#givat_morgan',
    hashtags: '#givat_morgan #שבת_בבוקר #שוק_איכרים #מורגן_היל #farmersmarket #israelisfamilies',
    notes: 'ריל חיי שגרה. צלם בשוק האיכרים בבוקר. משפחות, אוכל, ילדים. מוזיקה רכה ברקע.',
  },
  {
    id: 30006,
    title: 'שבת בבוקר במורגן היל — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-02T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שבת בבוקר במורגן היל נראית ככה —\nשוק האיכרים, קפה ביד, ילדים רצים בין הדוכנים,\nואוויר שמריח כמו שאוויר אמור להריח 🌿\n\nאתם גם כאן? תגידו שלום 👋\n\n#givat_morgan',
    hashtags: '#givat_morgan #שבת_בבוקר #שוק_איכרים #מורגן_היל #farmersmarket #israelisfamilies',
    notes: 'ריל חיי שגרה. צלם בשוק האיכרים בבוקר. משפחות, אוכל, ילדים. מוזיקה רכה ברקע.',
  },

  // ── Jun 4 — Small Moments Carousel ──────────────────────────────────────────
  {
    id: 30007,
    title: 'רגעים קטנים מהחיים פה — IG',
    platforms: ['ig'],
    date: new Date('2026-06-04T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'לא כל דבר צריך להיות אירוע גדול.\nלפעמים זה ערב סושי עם חברים.\nלפעמים קפה בדאונטאון.\nלפעמים הילדים משחקים ואתה רק מסתכל.\n\nהחיים הקטנים האלה — הם הסיבה שנשארנו ❤️\n\n#givat_morgan',
    hashtags: '#givat_morgan #חיי_קהילה #מורגן_היל #israelis #morganhill #bayarealife',
    notes: 'Photo dump אותנטי. תמונות לא מושלמות זה בסדר. ויב יומיומי וחמים.',
  },
  {
    id: 30008,
    title: 'רגעים קטנים מהחיים פה — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-04T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'לא כל דבר צריך להיות אירוע גדול.\nלפעמים זה ערב סושי עם חברים.\nלפעמים קפה בדאונטאון.\nלפעמים הילדים משחקים ואתה רק מסתכל.\n\nהחיים הקטנים האלה — הם הסיבה שנשארנו ❤️\n\n#givat_morgan',
    hashtags: '#givat_morgan #חיי_קהילה #מורגן_היל #israelis #morganhill #bayarealife',
    notes: 'Photo dump אותנטי. תמונות לא מושלמות זה בסדר. ויב יומיומי וחמים.',
  },

  // ── Jun 7 — Not Napa Reel ────────────────────────────────────────────────────
  {
    id: 30009,
    title: 'לא, זה לא נאפה — IG',
    platforms: ['ig'],
    date: new Date('2026-06-07T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'כן, זה לא נאפה.\nזה מורגן היל.\nוהיין לא פחות טוב, תאמינו לנו 🍷\n\n(ובלוני אוויר חם בדרך) 🎈\n\n#givat_morgan',
    hashtags: '#givat_morgan #יקב #מורגן_היל #נאפה_של_הדרום #winery #morganhill',
    notes: 'צלם ביקב מקומי. ויז\'ואל חזק. הומור ישראלי קצר ומדויק. פוטנציאל גבוה לשיתופים.',
  },
  {
    id: 30010,
    title: 'לא, זה לא נאפה — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-07T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'כן, זה לא נאפה.\nזה מורגן היל.\nוהיין לא פחות טוב, תאמינו לנו 🍷\n\n(ובלוני אוויר חם בדרך) 🎈\n\n#givat_morgan',
    hashtags: '#givat_morgan #יקב #מורגן_היל #נאפה_של_הדרום #winery #morganhill',
    notes: 'צלם ביקב מקומי. ויז\'ואל חזק. הומור ישראלי קצר ומדויק. פוטנציאל גבוה לשיתופים.',
  },

  // ── Jun 9 — Why Families Move Reel ──────────────────────────────────────────
  {
    id: 30011,
    title: 'למה משפחות ישראליות עוברות — IG',
    platforms: ['ig'],
    date: new Date('2026-06-09T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שאלו אותנו את זה הרבה פעמים.\nאז ניסינו לענות בריל אחד.\n\nפארקים שהילדים לא רוצים לעזוב.\nשבילים שמרגישים כמו חופשה.\nקהילה שמתחילה להרגיש כמו משפחה.\nמחירים שעדיין אפשר לנשום איתם.\n\nאם אתם שוקלים — שווה לדבר 💚\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #עוברים_לקליפורניה #israelifamilies #morganhill #realestate',
    notes: 'צלם בפארק Sobrato או השביל ב-Dunne Ave. משפחות, ילדים, טבע. ריל רגשי — הכי קרוב לסופט סייל.',
  },
  {
    id: 30012,
    title: 'למה משפחות ישראליות עוברות — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-09T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שאלו אותנו את זה הרבה פעמים.\nאז ניסינו לענות בריל אחד.\n\nפארקים שהילדים לא רוצים לעזוב.\nשבילים שמרגישים כמו חופשה.\nקהילה שמתחילה להרגיש כמו משפחה.\nמחירים שעדיין אפשר לנשום איתם.\n\nאם אתם שוקלים — שווה לדבר 💚\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #עוברים_לקליפורניה #israelifamilies #morganhill #realestate',
    notes: 'צלם בפארק Sobrato או השביל ב-Dunne Ave. משפחות, ילדים, טבע. ריל רגשי — הכי קרוב לסופט סייל.',
  },

  // ── Jun 11 — Favorite Downtown Carousel ─────────────────────────────────────
  {
    id: 30013,
    title: 'המקומות האהובים בדאונטאון — IG',
    platforms: ['ig'],
    date: new Date('2026-06-11T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'הדאונטאון של מורגן היל הוא קטן — אבל מושלם.\nהנה המקומות שחוזרים אליהם שוב ושוב:\n\n🍕 פיצה: [שם המקום]\n☕ קפה: Philz + [מקומי נוסף]\n🌮 טאקו: [שם המקום]\n🍺 בירה: [שם הבר]\n🍦 קינוח: [שם המקום]\n\nאיזה מקום הכי אהבתם? ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #דאונטאון_מורגן_היל #מסעדות #downtown #morganhill #foodie',
    notes: 'כל שקף = מקום אחד + תמונה + המלצה אחת שורה. שקף אחרון = שאלה לקהל. עדכן את שמות המקומות.',
  },
  {
    id: 30014,
    title: 'המקומות האהובים בדאונטאון — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-11T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'carousel',
    media: [],
    text: 'הדאונטאון של מורגן היל הוא קטן — אבל מושלם.\nהנה המקומות שחוזרים אליהם שוב ושוב:\n\n🍕 פיצה: [שם המקום]\n☕ קפה: Philz + [מקומי נוסף]\n🌮 טאקו: [שם המקום]\n🍺 בירה: [שם הבר]\n🍦 קינוח: [שם המקום]\n\nאיזה מקום הכי אהבתם? ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #דאונטאון_מורגן_היל #מסעדות #downtown #morganhill #foodie',
    notes: 'כל שקף = מקום אחד + תמונה + המלצה אחת שורה. שקף אחרון = שאלה לקהל. עדכן את שמות המקומות.',
  },

  // ── Jun 14 — Calm Day Reel ───────────────────────────────────────────────────
  {
    id: 30015,
    title: 'עוד יום רגוע במורגן היל — IG',
    platforms: ['ig'],
    date: new Date('2026-06-14T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'לא כל יום צריך להיות ה-best day ever.\nלפעמים זה רק יום רגיל.\nוגם זה מספיק יפה 🌿\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #חיי_שגרה #bayarealife #morganhill',
    notes: 'מונטאז׳ יומיומי — קפה, שביל, שקיעה, ילדים. לו-פרשר. לא צריך להיות מושלם.',
  },
  {
    id: 30016,
    title: 'עוד יום רגוע במורגן היל — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-14T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'לא כל יום צריך להיות ה-best day ever.\nלפעמים זה רק יום רגיל.\nוגם זה מספיק יפה 🌿\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #חיי_שגרה #bayarealife #morganhill',
    notes: 'מונטאז׳ יומיומי — קפה, שביל, שקיעה, ילדים. לו-פרשר. לא צריך להיות מושלם.',
  },

  // ── Jun 16 — Feels Like Home Reel ───────────────────────────────────────────
  {
    id: 30017,
    title: 'לאט לאט זה מרגיש כמו בית — IG',
    platforms: ['ig'],
    date: new Date('2026-06-16T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'בהתחלה זה היה מקום חדש.\nאחר כך זה היה השכונה שלנו.\nועכשיו — זה פשוט הבית.\n\nלאט לאט, רגע אחרי רגע.\nמורגן היל הפך להיות המקום שאנחנו לא מתכוונים לעזוב 💚\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #בית #קהילה #israelis #morganhill #community',
    notes: 'הריל הכי רגשי של החודש. צלם אירועים, שקיעות, משפחות, דאונטאון. עריכה איטית עם מוזיקה.',
  },
  {
    id: 30018,
    title: 'לאט לאט זה מרגיש כמו בית — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-16T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'בהתחלה זה היה מקום חדש.\nאחר כך זה היה השכונה שלנו.\nועכשיו — זה פשוט הבית.\n\nלאט לאט, רגע אחרי רגע.\nמורגן היל הפך להיות המקום שאנחנו לא מתכוונים לעזוב 💚\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #בית #קהילה #israelis #morganhill #community',
    notes: 'הריל הכי רגשי של החודש. צלם אירועים, שקיעות, משפחות, דאונטאון. עריכה איטית עם מוזיקה.',
  },

  // ── Jun 18 — FAQ Carousel ────────────────────────────────────────────────────
  {
    id: 30019,
    title: 'שאלות לפני מעבר למורגן היל — IG',
    platforms: ['ig'],
    date: new Date('2026-06-18T19:30:00'),
    status: 'draft',
    pillar: 'שאלת שבוע',
    type: 'carousel',
    media: [],
    text: 'קיבלנו את השאלות האלה כל כך הרבה פעמים — החלטנו לענות בפוסט אחד.\n\n❓ בתי הספר טובים?\n✅ כן — Morgan Hill Unified School District בדירוג גבוה.\n\n❓ כמה זמן לסיליקון ואלי?\n✅ 30–45 דקות לסן חוזה, Tesla, Apple.\n\n❓ כמה עולה לגור כאן?\n✅ זול יותר מסן חוזה — עם הרבה יותר מקום.\n\n❓ מה מזג האוויר?\n✅ שמש רוב השנה. קצת גשם בחורף.\n\n❓ יש קהילה ישראלית?\n✅ יש — וגבעת מורגן בנויה בשבילה 💚\n\nיש שאלה שלא ענינו? כתבו בתגובות ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #עוברים_לקליפורניה #bayarea #realestate #israelis',
    notes: 'הפוסט הכי ממיר לידים. כל שקף = שאלה + תשובה. שקף אחרון = CTA רך.',
  },
  {
    id: 30020,
    title: 'שאלות לפני מעבר למורגן היל — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-18T19:30:00'),
    status: 'draft',
    pillar: 'שאלת שבוע',
    type: 'carousel',
    media: [],
    text: 'קיבלנו את השאלות האלה כל כך הרבה פעמים — החלטנו לענות בפוסט אחד.\n\n❓ בתי הספר טובים?\n✅ כן — Morgan Hill Unified School District בדירוג גבוה.\n\n❓ כמה זמן לסיליקון ואלי?\n✅ 30–45 דקות לסן חוזה, Tesla, Apple.\n\n❓ כמה עולה לגור כאן?\n✅ זול יותר מסן חוזה — עם הרבה יותר מקום.\n\n❓ מה מזג האוויר?\n✅ שמש רוב השנה. קצת גשם בחורף.\n\n❓ יש קהילה ישראלית?\n✅ יש — וגבעת מורגן בנויה בשבילה 💚\n\nיש שאלה שלא ענינו? כתבו בתגובות ⬇️\n\n#givat_morgan',
    hashtags: '#givat_morgan #מורגן_היל #עוברים_לקליפורניה #bayarea #realestate #israelis',
    notes: 'הפוסט הכי ממיר לידים. כל שקף = שאלה + תשובה. שקף אחרון = CTA רך.',
  },

  // ── Jun 21 — Philz + Farmers Market Reel ────────────────────────────────────
  {
    id: 30021,
    title: 'פילז + שוק איכרים — IG',
    platforms: ['ig'],
    date: new Date('2026-06-21T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שלב 1: עוברים למורגן היל בגלל הבתים הגדולים.\nשלב 2: מגלים שיש Philz.\nשלב 3: מגלים שיש שוק איכרים.\nשלב 4: לא מבינים איך חיינו בלי זה.\n😅\n\n#givat_morgan',
    hashtags: '#givat_morgan #ישראלים_בקליפורניה #bayarealife #philz #farmersmarket #humor',
    notes: 'הומור Bay Area ישראלי. פורמט בשלבים — קל לצלם ולערוך. פוטנציאל שיתוף גבוה מאוד.',
  },
  {
    id: 30022,
    title: 'פילז + שוק איכרים — FB',
    platforms: ['fbg'],
    date: new Date('2026-06-21T19:30:00'),
    status: 'draft',
    pillar: 'תמונות חיים',
    type: 'reel',
    media: [],
    text: 'שלב 1: עוברים למורגן היל בגלל הבתים הגדולים.\nשלב 2: מגלים שיש Philz.\nשלב 3: מגלים שיש שוק איכרים.\nשלב 4: לא מבינים איך חיינו בלי זה.\n😅\n\n#givat_morgan',
    hashtags: '#givat_morgan #ישראלים_בקליפורניה #bayarealife #philz #farmersmarket #humor',
    notes: 'הומור Bay Area ישראלי. פורמט בשלבים — קל לצלם ולערוך. פוטנציאל שיתוף גבוה מאוד.',
  },
];
