// Monthly content fill — SBF + GM — Jun 5 through Jul 9, 2026
// IDs 50001–50069
// Fills daily posting gaps between existing calendar posts

export const MONTHLY_CALENDAR = {

  // ── SBF — Jun 5 through Jul 9 (fills off-days in existing calendar) ──────────
  sbf: [
    {
      id: 50001,
      title: 'Client Love — Jamie & Carlos',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-05T15:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: '⭐️ Client Love\n\n"Moshe made us feel like his only clients. We were nervous first-time buyers and he walked us through every single step. Closed in 18 days!"\n— Jamie & Carlos R., Morgan Hill\n\nThis is why I do what I do. 💚\n\n#morganhill #realestate #clientlove #firsttimebuyer #morganhillhomes',
    },
    {
      id: 50002,
      title: 'Weekend Vibes — Morgan Hill',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-07T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "This is what weekends look like in Morgan Hill 🌿\n\nFarmers market in the morning, wine tasting in the afternoon, dinner downtown.\n\nStill not sure why everyone isn't living here. 😄\n\nDM me to find out what it takes to make the move. 📩\n\n#morganhill #morganhilllife #bayarealiving #weekendvibes #realestate",
    },
    {
      id: 50003,
      title: 'SB9 — What It Means for You',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-06-09T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "🏗️ SB 9 — What It Means for Morgan Hill Homeowners\n\nCalifornia's SB 9 law allows homeowners to split their single-family lot and build up to 4 units.\n\nWhat this means for you:\n✅ More housing options\n✅ Potential rental income\n✅ Increased property value\n\nWant to know if your property qualifies? DM me. 📩\n\n#sb9 #morganhill #realestate #investment #calhousing",
    },
    {
      id: 50004,
      title: 'Why People Never Leave MH',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-11T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "There's a reason people who move to Morgan Hill never leave. 🌿\n\nThe trails, the wine country, the small-town feel — 30 minutes from Silicon Valley.\n\nThis isn't just real estate. It's a lifestyle upgrade.\n\nDM me to explore your options. 📩\n\n#morganhill #morganhillrealestate #bayarea #lifestyle #siliconvalley",
    },
    {
      id: 50005,
      title: 'Summer Seller Tips',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-06-13T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "📋 Thinking of selling this summer?\n\nHere's what most sellers don't know:\n\n✅ Homes listed June–August sell 9% faster on average\n✅ First 7 days = highest traffic — price it right from day 1\n✅ Declutter before photos — not after\n✅ Pre-inspection gives you control of the narrative\n\nReady to talk strategy? DM me. 📩\n\n#morganhill #sellyourhome #realestate #homeselling #bayarearealestate",
    },
    {
      id: 50006,
      title: 'Client Love — Sunnyvale to MH',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-15T15:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: '⭐️ Just heard from past clients — they celebrated their 1-year anniversary in their Morgan Hill home.\n\n"Best decision we ever made. We went from a 2BR apartment in Sunnyvale to a 4BR home with a yard. Same commute, completely different life."\n\nThis is what it\'s all about. 💚\n\n#morganhill #realestate #clientlove #morganhillhomes #bayarea',
    },
    {
      id: 50007,
      title: 'Mid-June Market Update',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-06-17T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'post',
      media: [],
      text: '📊 Mid-June Market Update — Morgan Hill\n\nMedian home price: $1.1M\nDays on market: 16 (down from 22 last quarter)\nList-to-sale ratio: 102%\n\nInventory is still tight. If you\'ve been waiting for prices to drop — the data says otherwise.\n\nLet\'s talk about your timeline. 📩\n\n#morganhill #realestate #marketupdate #bayarearealestate #homesales',
    },
    {
      id: 50008,
      title: 'Summer in MH — Lifestyle',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-19T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "Summer in Morgan Hill hits different 🌞\n\nUvas Creek. Coyote Lake. Anderson Lake.\nWine country 10 minutes away.\nFarmers market every weekend.\n\nThis is the Bay Area upgrade nobody talks about enough.\n\n#morganhill #bayarealiving #summer #morganhilllife #californialiving",
    },
    {
      id: 50009,
      title: "Father's Day Post",
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-21T09:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: "Happy Father's Day to all the dads out there 💚\n\nSome of my best clients are dads making the move for their families — more space, better schools, real outdoor life.\n\nIf making the move is on your mind, I'm here. 📩\n\n#fathersday #morganhill #realestate #familyfirst #morganhillhomes",
    },
    {
      id: 50010,
      title: 'MH Long-Term Investment',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-06-23T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "🏘️ Why Morgan Hill is one of the best long-term real estate investments in the Bay Area:\n\n📈 Home values up 34% in 5 years\n🏗️ Limited land for new development\n🚆 Caltrain extension planned\n🏫 Top-rated school district\n\nThe window won't be open forever.\n\nDM me to talk numbers. 📩\n\n#morganhill #realestate #investment #bayarearealestate #morganhillhomes",
    },
    {
      id: 50011,
      title: 'Paradise Valley Spotlight',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-25T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "Paradise Valley, Morgan Hill 🌅\n\nThis neighborhood doesn't get enough attention.\nTrails, views, open space — and homes that actually have room to breathe.\n\nDM me if you want to explore what's available here. 📩\n\n#morganhill #paradisevalley #bayarealiving #morganhillrealestate #neighborhoods",
    },
    {
      id: 50012,
      title: 'Pre-Approval Tips',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-06-27T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "📋 Getting pre-approved? Do this first:\n\n✅ Check your credit score (aim for 740+)\n✅ Don't open any new credit accounts\n✅ Document ALL income sources\n✅ Get pre-approved — not just pre-qualified\n✅ Shop 3+ lenders for best rate\n\nWant a referral to a great local lender? DM me. 📩\n\n#morganhill #firsttimebuyer #realestate #preapproval #bayarearealestate",
    },
    {
      id: 50013,
      title: '3 Closings in 3 Weeks',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-29T11:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: "🔑 3 clients. 3 closings. 3 weeks.\n\nMorgan Hill, Gilroy, and South San Jose.\n\nBuyers who act with clarity and strategy win in this market — even with rates where they are.\n\nReady to be next? Let's talk. 📩\n\n#morganhill #realestate #justclosed #bayarearealestate #clientwin",
    },
    {
      id: 50014,
      title: 'Mid-Year Market Update',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-07-01T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "📊 Mid-Year Real Estate Update — Bay Area South\n\nHalf the year is done. Here's what matters:\n\n🏡 Morgan Hill inventory: still low\n📈 Prices: holding strong\n⏳ Average days on market: 14\n💰 Rate trend: stabilizing\n\nQ3 is shaping up to be competitive. The best time to act is before everyone else does.\n\nDM me to build your Q3 strategy. 📩\n\n#realestate #bayarea #morganhill #marketupdate #q3",
    },
    {
      id: 50015,
      title: '4th of July — MH Lifestyle',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-03T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "Nothing better than 4th of July in a town that actually does it right 🎆\n\nMorgan Hill goes all out — parades, fireworks, the whole small-town summer experience.\n\nThis is the lifestyle. 🇺🇸\n\n#morganhill #4thofjuly #independenceday #morganhilllife #bayarea",
    },
    {
      id: 50016,
      title: '4th of July',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-04T10:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: "Happy 4th of July! 🎆🇺🇸\n\nWishing everyone in the Morgan Hill community a safe, joyful, and beautiful Independence Day.\n\nProud to call this place home. 💚\n\n#morganhill #4thofjuly #independenceday #morganhillrealestate",
    },
    {
      id: 50017,
      title: 'Summer Buyer Tips',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-07-06T09:00:00'),
      status: 'scheduled',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "☀️ Summer Buyer Tips for Morgan Hill:\n\n🏡 Inventory peaks in July — more choices\n💨 Less competition than spring — better terms\n📅 Closing before school starts? Act NOW\n🏊 Families: proximity to aquatic center, trails, and parks matters\n\nDon't wait for the perfect moment. The market moves fast.\n\nDM me. 📩\n\n#morganhill #realestate #summerbuying #bayarearealestate #homebuyer",
    },
    {
      id: 50018,
      title: 'Silicon Valley + MH Lifestyle',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-07T11:00:00'),
      status: 'scheduled',
      pillar: 'Reach',
      type: 'post',
      media: [],
      text: "Reminder: you don't have to choose between Silicon Valley career and California lifestyle. 🌿\n\nMorgan Hill gives you both.\n\n30 min to Tesla. 35 min to Apple.\nAnd this is your backyard.\n\n#morganhill #bayarealiving #siliconvalley #californialife #morganhillrealestate",
    },
    {
      id: 50019,
      title: 'Closing Story — Offer #5',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-09T11:00:00'),
      status: 'scheduled',
      pillar: 'Trust',
      type: 'post',
      media: [],
      text: "🔑 Closed this week in Morgan Hill.\n\nMy clients came to me after losing 4 offers elsewhere. We changed strategy — focused on terms, not just price.\n\nOffer 5: accepted.\n\nThe right strategy wins. 💪\n\n#morganhill #realestate #justclosed #buyingstrategy #bayarearealestate",
    },
  ],

  // ── GM — Jun 5 through Jul 9 (fills gaps + extends past Jun 21) ──────────────
  gm: [
    // ── Jun 5 (Fri) — שאלת שבת ────────────────────────────────────────────────
    {
      id: 50020,
      title: 'שאלת שבת — Jun 5 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-05T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום מגבעת מורגן 🕯️\n\nמה התוכניות שלכם הסוף שבוע הזה?\nספרו לנו בתגובות ⬇️\n\n#givat_morgan #שבת_שלום #מורגן_היל #ישראלים_בבייאריאה',
    },
    {
      id: 50021,
      title: 'שאלת שבת — Jun 5 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-05T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום מגבעת מורגן 🕯️\n\nמה התוכניות שלכם הסוף שבוע הזה?\nספרו לנו בתגובות ⬇️\n\n#givat_morgan #שבת_שלום #מורגן_היל #ישראלים_בבייאריאה',
    },

    // ── Jun 8 (Sun) — תמונות חיים ────────────────────────────────────────────
    {
      id: 50022,
      title: 'יום ראשון — Jun 8 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-08T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון במורגן היל 🌿\n\nשמש, קפה, ואנשים שיודעים איך לנוח.\n\nאיפה אתם הבוקר? ⬇️\n\n#givat_morgan #מורגן_היל #יום_ראשון #bayarealife',
    },
    {
      id: 50023,
      title: 'יום ראשון — Jun 8 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-08T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון במורגן היל 🌿\n\nשמש, קפה, ואנשים שיודעים איך לנוח.\n\nאיפה אתם הבוקר? ⬇️\n\n#givat_morgan #מורגן_היל #יום_ראשון #bayarealife',
    },

    // ── Jun 10 (Tue) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50024,
      title: 'Pearson Park — Jun 10 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-10T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'הדבר הכי טוב שגילינו במורגן היל השבוע 🌟\n\nPearson Park — אחד הפארקים הכי יפים ושקטים שיש.\nמושלם לבוקר עם הילדים או ריצה של ערב.\n\nהכרתם? ⬇️\n\n#givat_morgan #מורגן_היל #פארק #pearsonpark #bayarea',
    },
    {
      id: 50025,
      title: 'Pearson Park — Jun 10 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-10T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'הדבר הכי טוב שגילינו במורגן היל השבוע 🌟\n\nPearson Park — אחד הפארקים הכי יפים ושקטים שיש.\nמושלם לבוקר עם הילדים או ריצה של ערב.\n\nהכרתם? ⬇️\n\n#givat_morgan #מורגן_היל #פארק #pearsonpark #bayarea',
    },

    // ── Jun 12 (Fri) — שאלת שבת ─────────────────────────────────────────────
    {
      id: 50026,
      title: 'שאלת שבת — Jun 12 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-12T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שישי טוב! 🕯️\n\nשאלת השבוע — מה הספוט האהוב עליכם לקפה בסביבה?\nPhilz? Luxe? מקום אחר? נרצה לדעת! ☕\n\n#givat_morgan #מורגן_היל #שבת #קפה #ישראלים_בבייאריאה',
    },
    {
      id: 50027,
      title: 'שאלת שבת — Jun 12 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-12T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שישי טוב! 🕯️\n\nשאלת השבוע — מה הספוט האהוב עליכם לקפה בסביבה?\nPhilz? Luxe? מקום אחר? נרצה לדעת! ☕\n\n#givat_morgan #מורגן_היל #שבת #קפה #ישראלים_בבייאריאה',
    },

    // ── Jun 13 (Sat) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50028,
      title: 'שבת בדאונטאון — Jun 13 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-13T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום שבת בדאונטאון מורגן היל ☀️\n\nשוק, קפה, טיול קצר — זה כל מה שצריך.\n\nאיפה אתם היום? 🌿\n\n#givat_morgan #מורגן_היל #שבת #downtown #morganhill',
    },
    {
      id: 50029,
      title: 'שבת בדאונטאון — Jun 13 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-13T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום שבת בדאונטאון מורגן היל ☀️\n\nשוק, קפה, טיול קצר — זה כל מה שצריך.\n\nאיפה אתם היום? 🌿\n\n#givat_morgan #מורגן_היל #שבת #downtown #morganhill',
    },

    // ── Jun 15 (Mon) — שאלת שבוע ────────────────────────────────────────────
    {
      id: 50030,
      title: 'שאלת שבוע — Jun 15 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-15T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nמה הדבר הראשון שאתם ממליצים לאנשים חדשים לעשות במורגן היל?\n\nשתפו בתגובות — אתם תמיד יודעים הכי טוב! ⬇️\n\n#givat_morgan #מורגן_היל #קהילה #ישראלים_בקליפורניה',
    },
    {
      id: 50031,
      title: 'שאלת שבוע — Jun 15 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-15T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nמה הדבר הראשון שאתם ממליצים לאנשים חדשים לעשות במורגן היל?\n\nשתפו בתגובות — אתם תמיד יודעים הכי טוב! ⬇️\n\n#givat_morgan #מורגן_היל #קהילה #ישראלים_בקליפורניה',
    },

    // ── Jun 17 (Wed) — סקר מקומי ────────────────────────────────────────────
    {
      id: 50032,
      title: 'סקר יקבים — Jun 17 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-17T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'סקר מקומי 📊\n\nאיזה יקב אתם הכי אוהבים באזור?\n\nA: Guglielmo Winery\nB: Clos LaChance\nC: אחר — ספרו לנו!\n\n🍷 ⬇️\n\n#givat_morgan #מורגן_היל #יקב #winery #bayareawine',
    },
    {
      id: 50033,
      title: 'סקר יקבים — Jun 17 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-17T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'סקר מקומי 📊\n\nאיזה יקב אתם הכי אוהבים באזור?\n\nA: Guglielmo Winery\nB: Clos LaChance\nC: אחר — ספרו לנו!\n\n🍷 ⬇️\n\n#givat_morgan #מורגן_היל #יקב #winery #bayareawine',
    },

    // ── Jun 19 (Fri) — שאלת שבת ─────────────────────────────────────────────
    {
      id: 50034,
      title: 'שאלת שבת 4th July — Jun 19 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-19T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שישי טוב! 🕯️\n\nה-4th of July מתקרב — איך אתם חוגגים?\nאירוע קהילתי? ברביקיו? זיקוקים?\n\nספרו לנו! 🎆⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #קיץ #ישראלים_בקליפורניה',
    },
    {
      id: 50035,
      title: 'שאלת שבת 4th July — Jun 19 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-19T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שישי טוב! 🕯️\n\nה-4th of July מתקרב — איך אתם חוגגים?\nאירוע קהילתי? ברביקיו? זיקוקים?\n\nספרו לנו! 🎆⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #קיץ #ישראלים_בקליפורניה',
    },

    // ── Jun 20 (Sat) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50036,
      title: 'קיץ במורגן היל — Jun 20 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-20T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'סוף שבוע של קיץ 🌞\n\nמורגן היל בקיץ זה משהו אחר לגמרי.\nאוויר יבש, שמיים כחולים, וכולם בחוץ.\n\nאיפה אתם היום? ☀️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },
    {
      id: 50037,
      title: 'קיץ במורגן היל — Jun 20 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-20T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'סוף שבוע של קיץ 🌞\n\nמורגן היל בקיץ זה משהו אחר לגמרי.\nאוויר יבש, שמיים כחולים, וכולם בחוץ.\n\nאיפה אתם היום? ☀️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },

    // ── Jun 21 (Sun) — Father's Day ──────────────────────────────────────────
    {
      id: 50038,
      title: "יום האב — Jun 21 — IG",
      platforms: ['ig'],
      date: new Date('2026-06-21T09:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום האב שמח לכל האבות שלנו בגבעת מורגן 💚\n\nאתם בונים כאן בית, קהילה, ועתיד לילדים שלכם.\nזה לא מובן מאליו — תודה.\n\nאבא — מה המתנה הכי טובה שקיבלת? ⬇️\n\n#givat_morgan #יום_האב #fathersday #מורגן_היל',
    },
    {
      id: 50039,
      title: "יום האב — Jun 21 — FB",
      platforms: ['fbg'],
      date: new Date('2026-06-21T09:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום האב שמח לכל האבות שלנו בגבעת מורגן 💚\n\nאתם בונים כאן בית, קהילה, ועתיד לילדים שלכם.\nזה לא מובן מאליו — תודה.\n\nאבא — מה המתנה הכי טובה שקיבלת? ⬇️\n\n#givat_morgan #יום_האב #fathersday #מורגן_היל',
    },

    // ── Jun 22 (Sun) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50040,
      title: 'טיולי קיץ — Jun 22 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-22T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון טוב מגבעת מורגן 🌿\n\nהקיץ כבר כאן — מישהו מתכנן טיול לפארק היום?\n\nUvas Reservoir, Coyote Lake, Dunne Ave Trail — מה הבחירה שלכם? ⬇️\n\n#givat_morgan #מורגן_היל #טיול #summer #bayarea',
    },
    {
      id: 50041,
      title: 'טיולי קיץ — Jun 22 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-22T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון טוב מגבעת מורגן 🌿\n\nהקיץ כבר כאן — מישהו מתכנן טיול לפארק היום?\n\nUvas Reservoir, Coyote Lake, Dunne Ave Trail — מה הבחירה שלכם? ⬇️\n\n#givat_morgan #מורגן_היל #טיול #summer #bayarea',
    },

    // ── Jun 23 (Mon) — שאלת שבוע ────────────────────────────────────────────
    {
      id: 50042,
      title: 'כמה זמן גרים — Jun 23 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-23T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nכמה זמן אתם גרים במורגן היל?\n\nA: פחות משנה\nB: 1–3 שנים\nC: 3–5 שנים\nD: יותר מ-5 שנים\n\nוספרו — מה הביא אתכם לכאן? ⬇️\n\n#givat_morgan #קהילה #מורגן_היל',
    },
    {
      id: 50043,
      title: 'כמה זמן גרים — Jun 23 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-23T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nכמה זמן אתם גרים במורגן היל?\n\nA: פחות משנה\nB: 1–3 שנים\nC: 3–5 שנים\nD: יותר מ-5 שנים\n\nוספרו — מה הביא אתכם לכאן? ⬇️\n\n#givat_morgan #קהילה #מורגן_היל',
    },

    // ── Jun 24 (Tue) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50044,
      title: '3 דברים בקיץ — Jun 24 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-24T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'שלושה דברים שאוהבים בקיץ במורגן היל ☀️\n\n1. השקיעות — כבר ראיתם?\n2. Uvas Creek — המים קרים ומושלמים\n3. הדאונטאון בערב — חי ומלא אנרגיה\n\nמה אתם מוסיפים לרשימה? ⬇️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },
    {
      id: 50045,
      title: '3 דברים בקיץ — Jun 24 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-24T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'שלושה דברים שאוהבים בקיץ במורגן היל ☀️\n\n1. השקיעות — כבר ראיתם?\n2. Uvas Creek — המים קרים ומושלמים\n3. הדאונטאון בערב — חי ומלא אנרגיה\n\nמה אתם מוסיפים לרשימה? ⬇️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },

    // ── Jun 26 (Thu) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50046,
      title: 'שבילים — Jun 26 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-26T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'לפעמים הדבר הכי טוב שאתה יכול לעשות זה פשוט לצאת לטיול 🌿\n\nהשבילים של מורגן היל הם אחת הסיבות שאנחנו גרים כאן.\nקצת טבע, קצת שקט — ממש בפינה.\n\n#givat_morgan #מורגן_היל #שבילים #hiking #bayarea',
    },
    {
      id: 50047,
      title: 'שבילים — Jun 26 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-26T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'לפעמים הדבר הכי טוב שאתה יכול לעשות זה פשוט לצאת לטיול 🌿\n\nהשבילים של מורגן היל הם אחת הסיבות שאנחנו גרים כאן.\nקצת טבע, קצת שקט — ממש בפינה.\n\n#givat_morgan #מורגן_היל #שבילים #hiking #bayarea',
    },

    // ── Jun 27 (Fri) — שאלת שבת ─────────────────────────────────────────────
    {
      id: 50048,
      title: 'שאלת שבת מסעדות — Jun 27 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-27T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום! 🕯️\n\nשאלה לסוף השבוע — מה המסעדה האהובה עליכם בדאונטאון מורגן היל?\nשתפו — אנחנו בונים רשימה! 🍽️\n\n#givat_morgan #מורגן_היל #מסעדות #שבת #morganhill',
    },
    {
      id: 50049,
      title: 'שאלת שבת מסעדות — Jun 27 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-27T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום! 🕯️\n\nשאלה לסוף השבוע — מה המסעדה האהובה עליכם בדאונטאון מורגן היל?\nשתפו — אנחנו בונים רשימה! 🍽️\n\n#givat_morgan #מורגן_היל #מסעדות #שבת #morganhill',
    },

    // ── Jun 29 (Mon) — שאלת שבוע ────────────────────────────────────────────
    {
      id: 50050,
      title: 'תוכניות קיץ — Jun 29 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-29T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nיולי כבר פה — מה התוכניות שלכם לקיץ?\n\nחופשה? ביקור בישראל? נשארים כאן ונהנים?\nספרו לנו! ✈️☀️\n\n#givat_morgan #מורגן_היל #קיץ #קהילה',
    },
    {
      id: 50051,
      title: 'תוכניות קיץ — Jun 29 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-29T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nיולי כבר פה — מה התוכניות שלכם לקיץ?\n\nחופשה? ביקור בישראל? נשארים כאן ונהנים?\nספרו לנו! ✈️☀️\n\n#givat_morgan #מורגן_היל #קיץ #קהילה',
    },

    // ── Jun 30 (Tue) — תמונות חיים ──────────────────────────────────────────
    {
      id: 50052,
      title: 'חצי שנה — Jun 30 — IG',
      platforms: ['ig'],
      date: new Date('2026-06-30T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'חצי שנה עברה — ואנחנו עדיין לא מצליחים להפסיק לאהוב את המקום הזה 💚\n\nמורגן היל, תודה על כל הרגעים היפים.\nעוד חצי שנה טובה לפנינו! 🥂\n\n#givat_morgan #מורגן_היל #קהילה #bayarea',
    },
    {
      id: 50053,
      title: 'חצי שנה — Jun 30 — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-30T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'חצי שנה עברה — ואנחנו עדיין לא מצליחים להפסיק לאהוב את המקום הזה 💚\n\nמורגן היל, תודה על כל הרגעים היפים.\nעוד חצי שנה טובה לפנינו! 🥂\n\n#givat_morgan #מורגן_היל #קהילה #bayarea',
    },

    // ── Jul 1 (Wed) — סקר מקומי ─────────────────────────────────────────────
    {
      id: 50054,
      title: 'סקר 4th July — Jul 1 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-01T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'ה-4th of July מגיע! 🎆\n\nסקר — איפה הזיקוקים הכי טובים באזור?\n\nA: מורגן היל\nB: גילרוי\nC: סן חוזה\nD: מקום אחר\n\n⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #זיקוקים #bayarea',
    },
    {
      id: 50055,
      title: 'סקר 4th July — Jul 1 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-01T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'ה-4th of July מגיע! 🎆\n\nסקר — איפה הזיקוקים הכי טובים באזור?\n\nA: מורגן היל\nB: גילרוי\nC: סן חוזה\nD: מקום אחר\n\n⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #זיקוקים #bayarea',
    },

    // ── Jul 3 (Fri) — שאלת שבת + 4th of July ───────────────────────────────
    {
      id: 50056,
      title: 'שבת + 4th July — Jul 3 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-03T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום + Happy 4th of July weekend! 🕯️🎆\n\nשני חגים, עם אחד — אנחנו ישראלים ואמריקאים, ויודעים לחגוג את שניהם 🇮🇱🇺🇸\n\nאיך אתם חוגגים הסוף שבוע? ⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #שבת #ישראלים_בקליפורניה',
    },
    {
      id: 50057,
      title: 'שבת + 4th July — Jul 3 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-03T19:30:00'),
      status: 'scheduled',
      pillar: 'שאלת שבת',
      type: 'post',
      media: [],
      text: 'שבת שלום + Happy 4th of July weekend! 🕯️🎆\n\nשני חגים, עם אחד — אנחנו ישראלים ואמריקאים, ויודעים לחגוג את שניהם 🇮🇱🇺🇸\n\nאיך אתם חוגגים הסוף שבוע? ⬇️\n\n#givat_morgan #מורגן_היל #4thofjuly #שבת #ישראלים_בקליפורניה',
    },

    // ── Jul 4 (Sat) — 4th of July ────────────────────────────────────────────
    {
      id: 50058,
      title: '4th of July — Jul 4 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-04T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'Happy 4th of July! 🎆🇺🇸\n\nלכל קהילת גבעת מורגן — שתהיה חגיגה מדהימה!\nבין אם אתם בברביקיו, בזיקוקים, או בשקט בבית — תיהנו מהיום הזה 💚\n\n#givat_morgan #4thofjuly #independenceday #מורגן_היל #ישראלים_בקליפורניה',
    },
    {
      id: 50059,
      title: '4th of July — Jul 4 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-04T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'Happy 4th of July! 🎆🇺🇸\n\nלכל קהילת גבעת מורגן — שתהיה חגיגה מדהימה!\nבין אם אתם בברביקיו, בזיקוקים, או בשקט בבית — תיהנו מהיום הזה 💚\n\n#givat_morgan #4thofjuly #independenceday #מורגן_היל #ישראלים_בקליפורניה',
    },

    // ── Jul 5 (Sun) — תמונות חיים ───────────────────────────────────────────
    {
      id: 50060,
      title: 'אחרי 4th July — Jul 5 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-05T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון אחרי ה-4th 😴☕\n\nהכי טוב: קפה בחוץ, בלי תוכניות, ומשפחה.\nזה מורגן היל בקיץ 💚\n\n#givat_morgan #מורגן_היל #קיץ #yom_rishon #morganhill',
    },
    {
      id: 50061,
      title: 'אחרי 4th July — Jul 5 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-05T10:00:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'יום ראשון אחרי ה-4th 😴☕\n\nהכי טוב: קפה בחוץ, בלי תוכניות, ומשפחה.\nזה מורגן היל בקיץ 💚\n\n#givat_morgan #מורגן_היל #קיץ #yom_rishon #morganhill',
    },

    // ── Jul 6 (Mon) — שאלת שבוע ─────────────────────────────────────────────
    {
      id: 50062,
      title: 'קייטנות — Jul 6 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-06T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nלאלו שיש ילדים — איזה קייטנה אתם ממליצים השנה?\n\nנרצה לשמוע מניסיון אישי! ⬇️\n\n#givat_morgan #מורגן_היל #ילדים #קייטנה #קהילה',
    },
    {
      id: 50063,
      title: 'קייטנות — Jul 6 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-06T09:00:00'),
      status: 'scheduled',
      pillar: 'שאלת שבוע',
      type: 'post',
      media: [],
      text: 'שאלת השבוע 💬\n\nלאלו שיש ילדים — איזה קייטנה אתם ממליצים השנה?\n\nנרצה לשמוע מניסיון אישי! ⬇️\n\n#givat_morgan #מורגן_היל #ילדים #קייטנה #קהילה',
    },

    // ── Jul 7 (Tue) — תמונות חיים ───────────────────────────────────────────
    {
      id: 50064,
      title: 'בוקר קיץ — Jul 7 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-07T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'אמצע הקיץ ואנחנו עדיין מתפלאים כל בוקר מחדש ☀️\n\nמורגן היל בבוקר — שקט, יפה, ומרגיש כמו בית.\n\n#givat_morgan #מורגן_היל #בוקר #קיץ #bayarea',
    },
    {
      id: 50065,
      title: 'בוקר קיץ — Jul 7 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-07T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'אמצע הקיץ ואנחנו עדיין מתפלאים כל בוקר מחדש ☀️\n\nמורגן היל בבוקר — שקט, יפה, ומרגיש כמו בית.\n\n#givat_morgan #מורגן_היל #בוקר #קיץ #bayarea',
    },

    // ── Jul 8 (Wed) — סקר מקומי ─────────────────────────────────────────────
    {
      id: 50066,
      title: 'סקר פארקים — Jul 8 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-08T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'סקר מקומי ☀️\n\nמה הפארק / שביל הכי אהוב עליכם באזור מורגן היל?\n\nA: Dunne Ave Trail\nB: Coyote Lake\nC: Uvas Reservoir\nD: Sobrato Park\n\n⬇️\n\n#givat_morgan #מורגן_היל #פארק #hiking #bayarea',
    },
    {
      id: 50067,
      title: 'סקר פארקים — Jul 8 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-08T09:00:00'),
      status: 'scheduled',
      pillar: 'סקר מקומי',
      type: 'post',
      media: [],
      text: 'סקר מקומי ☀️\n\nמה הפארק / שביל הכי אהוב עליכם באזור מורגן היל?\n\nA: Dunne Ave Trail\nB: Coyote Lake\nC: Uvas Reservoir\nD: Sobrato Park\n\n⬇️\n\n#givat_morgan #מורגן_היל #פארק #hiking #bayarea',
    },

    // ── Jul 9 (Thu) — תמונות חיים ───────────────────────────────────────────
    {
      id: 50068,
      title: 'רשימת קיץ — Jul 9 — IG',
      platforms: ['ig'],
      date: new Date('2026-07-09T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'אנחנו כבר ביולי ועדיין לא עשיתם הכל? 😄\n\nרשימת קיץ מומלצת:\n✅ שוק האיכרים\n✅ טעימות ביקב\n✅ ארוחת ערב בדאונטאון\n✅ הדרכה בשביל\n✅ בריכה ב-Aquatic Center\n\nמה חסר לכם? ⬇️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },
    {
      id: 50069,
      title: 'רשימת קיץ — Jul 9 — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-09T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'post',
      media: [],
      text: 'אנחנו כבר ביולי ועדיין לא עשיתם הכל? 😄\n\nרשימת קיץ מומלצת:\n✅ שוק האיכרים\n✅ טעימות ביקב\n✅ ארוחת ערב בדאונטאון\n✅ הדרכה בשביל\n✅ בריכה ב-Aquatic Center\n\nמה חסר לכם? ⬇️\n\n#givat_morgan #מורגן_היל #קיץ #summer #morganhill',
    },
  ],
};
