// Draft ideas — SBF + GM
// IDs 40001–40013
// Added from filmed content: Paradise Valley, Aquatic Center, New Build, Coyote Estates

export const DRAFT_IDEAS = {

  sbf: [
    {
      id: 40012,
      title: 'Coyote Estates Reel',
      platforms: ['ig', 'fb'],
      date: new Date('2026-06-10T11:00:00'),
      status: 'draft',
      pillar: 'Reach',
      type: 'reel',
      media: [],
      text: "This is still the Bay Area. 👀\n\nCoyote Estates, Morgan Hill — where the streets are quiet, the hills are right there, and you actually have a backyard.\n\nSilicon Valley is 30 minutes away.\nThis life is a lot closer than you think.\n\nDM me to learn more. 📩\n\n#morganhill #coyoteestates #bayarea #siliconvalley #morganhillrealestate #caliving",
    },
    {
      id: 40001,
      title: 'Paradise Valley Reel',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-02T11:00:00'),
      status: 'draft',
      pillar: 'Reach',
      type: 'reel',
      media: [],
      text: "This is what your backyard could look like. 🌅\n\nParadise Valley, Morgan Hill — one of the Bay Area's best-kept secrets.\nHiking trails, open skies, and homes that give you room to breathe.\n\n30 miles from Silicon Valley. A world away from everything else.\n\nDM me if you're ready to make the move. 📩\n\n#morganhill #paradisevalley #bayarealiving #siliconvalleyhomes #morganhillrealestate",
    },
    {
      id: 40002,
      title: 'Aquatic Center Reel',
      platforms: ['ig', 'fb'],
      date: new Date('2026-07-05T11:00:00'),
      status: 'draft',
      pillar: 'Reach',
      type: 'reel',
      media: [],
      text: "Most neighborhoods have a pool.\nMorgan Hill has THIS. 🌊\n\nThe Morgan Hill Aquatic Center — Olympic-size pool, slides, splash zone.\nYear-round. Family-friendly. Right in your neighborhood.\n\nThis is what living in Morgan Hill feels like. 💚\n\n#morganhill #aquaticcenter #bayareafamilies #morganhilllife #familyliving",
    },
    {
      id: 40003,
      title: 'New Build — Buyer Tips',
      platforms: ['ig', 'fb', 'li'],
      date: new Date('2026-07-08T09:00:00'),
      status: 'draft',
      pillar: 'Useful',
      type: 'carousel',
      media: [],
      text: "Thinking about buying new construction in Morgan Hill? 🏗️\n\nHere's what I tell every client:\n\n✅ You choose finishes, layout, sometimes even the lot\n✅ Builder warranties protect you for years\n✅ No competing with 10 other offers\n⚠️ But — the builder's agent works for the builder, not you\n\nHaving your own agent in a new build costs you nothing.\nAnd it could save you thousands.\n\nDM me before you walk into that model home. 📩\n\n#newconstruction #morganhill #buyeradvice #realestate #firsttimebuyer",
    },
  ],

  gm: [
    {
      id: 40004,
      title: 'Paradise Valley — IG',
      platforms: ['ig'],
      date: new Date('2026-06-25T19:30:00'),
      status: 'draft',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'מצאנו את הספוט הכי יפה במורגן היל — ומסיבה מה שמרנו אותו לעצמנו? 🌅\n\nParadise Valley, פחות מ-10 דקות מהבית.\nשבילים, שקיעות, ואוויר שמריח כמו חופשה.\n\nזה קיים פה. ואנחנו גרים כאן 💚\n\n#givat_morgan #מורגן_היל #paradisevalley #bayarea #ישראלים_בקליפורניה',
    },
    {
      id: 40005,
      title: 'Paradise Valley — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-25T19:30:00'),
      status: 'draft',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'מצאנו את הספוט הכי יפה במורגן היל — ומסיבה מה שמרנו אותו לעצמנו? 🌅\n\nParadise Valley, פחות מ-10 דקות מהבית.\nשבילים, שקיעות, ואוויר שמריח כמו חופשה.\n\nזה קיים פה. ואנחנו גרים כאן 💚\n\n#givat_morgan #מורגן_היל #paradisevalley #bayarea #ישראלים_בקליפורניה',
    },
    {
      id: 40006,
      title: 'Aquatic Center — IG',
      platforms: ['ig'],
      date: new Date('2026-06-28T19:30:00'),
      status: 'draft',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'חיכינו לקיץ כדי לדבר על זה ☀️\n\nמרכז המים של מורגן היל — בריכה אולימפית, מגלשות, אזור משחקים לילדים.\nהילדים לא רוצים לצאת משם. ואנחנו מבינים אותם.\n\nמי כבר מכיר את המקום? ⬇️\n\n#givat_morgan #מורגן_היל #בריכה #קיץ #ילדים #morganhill',
    },
    {
      id: 40007,
      title: 'Aquatic Center — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-28T19:30:00'),
      status: 'draft',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'חיכינו לקיץ כדי לדבר על זה ☀️\n\nמרכז המים של מורגן היל — בריכה אולימפית, מגלשות, אזור משחקים לילדים.\nהילדים לא רוצים לצאת משם. ואנחנו מבינים אותם.\n\nמי כבר מכיר את המקום? ⬇️\n\n#givat_morgan #מורגן_היל #בריכה #קיץ #ילדים #morganhill',
    },
    {
      id: 40008,
      title: 'New Build — IG',
      platforms: ['ig'],
      date: new Date('2026-07-02T19:30:00'),
      status: 'draft',
      pillar: 'שאלת שבוע',
      type: 'carousel',
      media: [],
      text: 'יש פרויקטים חדשים שמתפתחים במורגן היל 🏗️\n\nבנייה חדשה = בחירת גימור, אין מלחמות מחיר, ביטחון של אחריות.\n\nמישהו כאן עבר לבית חדש מהקבלן? איך הייתה החוויה? ⬇️\n\n#givat_morgan #מורגן_היל #נדלן #בנייה_חדשה #newconstruction',
    },
    {
      id: 40009,
      title: 'New Build — FB',
      platforms: ['fbg'],
      date: new Date('2026-07-02T19:30:00'),
      status: 'draft',
      pillar: 'שאלת שבוע',
      type: 'carousel',
      media: [],
      text: 'יש פרויקטים חדשים שמתפתחים במורגן היל 🏗️\n\nבנייה חדשה = בחירת גימור, אין מלחמות מחיר, ביטחון של אחריות.\n\nמישהו כאן עבר לבית חדש מהקבלן? איך הייתה החוויה? ⬇️\n\n#givat_morgan #מורגן_היל #נדלן #בנייה_חדשה #newconstruction',
    },

    // ── Coyote Estates Reel ──────────────────────────────────────────────────
    {
      id: 40013,
      title: 'Coyote Estates Reel — IG',
      platforms: ['ig'],
      date: new Date('2026-06-02T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'הכרתם את זה? 👀\n\nCoyote Estates — שכונה שקטה, ירוקה, עם בתים גדולים ופארק ממש בפינה.\nהרים ברקע, ילדים משחקים בחוץ, ואנשים שאוהבים לגור כאן.\n\nזה מורגן היל. 💚\n\n#givat_morgan #מורגן_היל #coyoteestates #bayarea #ישראלים_בקליפורניה',
    },
    {
      id: 40014,
      title: 'Coyote Estates Reel — FB',
      platforms: ['fbg'],
      date: new Date('2026-06-02T19:30:00'),
      status: 'scheduled',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'הכרתם את זה? 👀\n\nCoyote Estates — שכונה שקטה, ירוקה, עם בתים גדולים ופארק ממש בפינה.\nהרים ברקע, ילדים משחקים בחוץ, ואנשים שאוהבים לגור כאן.\n\nזה מורגן היל. 💚\n\n#givat_morgan #מורגן_היל #coyoteestates #bayarea #ישראלים_בקליפורניה',
    },

    // ── Published: Crab Crawl @ Terra Amico Reel (posted Sun May 31) ─────────
    {
      id: 40010,
      title: 'Crab Crawl @ Terra Amico — IG',
      platforms: ['ig'],
      date: new Date('2026-05-31T19:30:00'),
      status: 'published',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'קראב קרול במורגן היל 🦀\n\nיצאנו לחגוג את אחד האירועים הכי מיוחדים בעיר.\nמסעדה אחרי מסעדה, צבאים טריים, אנשים מגניבים — וכל זה ממש בדאונטאון שלנו.\n\nTerra Amico — אחד מהספוטים שלא מפספסים 🍽️\n\nזה מורגן היל. ❤️\n\n#givat_morgan #מורגן_היל #crabcrawl #terraAmico #morganhill #bayareafood #דאונטאון',
    },
    {
      id: 40011,
      title: 'Crab Crawl @ Terra Amico — FB',
      platforms: ['fb', 'fbg'],
      date: new Date('2026-05-31T19:30:00'),
      status: 'published',
      pillar: 'תמונות חיים',
      type: 'reel',
      media: [],
      text: 'קראב קרול במורגן היל 🦀\n\nיצאנו לחגוג את אחד האירועים הכי מיוחדים בעיר.\nמסעדה אחרי מסעדה, צבאים טריים, אנשים מגניבים — וכל זה ממש בדאונטאון שלנו.\n\nTerra Amico — אחד מהספוטים שלא מפספסים 🍽️\n\nזה מורגן היל. ❤️\n\n#givat_morgan #מורגן_היל #crabcrawl #terraAmico #morganhill #bayareafood #דאונטאון',
    },
  ],
};
